service: the-movie

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage}
  environment:
    MONGO_CONNECTION: mongodb+srv://sebastian-aldana:OMXrgjzOZp5FwhYq@the-movie.2gebb7m.mongodb.net/?retryWrites=true&w=majority
    JWT_SECRET: test

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
