service: the-movie

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage}
  environment:
    MONGO_CONNECTION: ${env:MONGO_CONNECTION}
    JWT_SECRET: ${env:JWT_SECRET}

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
